"""Initial_migration

Revision ID: 1aa521440427
Revises: 
Create Date: 2024-10-21 22:04:32.846318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa521440427'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_full_export',
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('classid', sa.String(), nullable=True),
    sa.Column('instanceid', sa.String(), nullable=True),
    sa.Column('real_instance', sa.String(), nullable=True),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.Column('base_id', sa.Integer(), nullable=True),
    sa.Column('float', sa.Double(), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('paintseed', sa.Integer(), nullable=True),
    sa.Column('paintindex', sa.Integer(), nullable=True),
    sa.Column('stickers', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('chance_to_transfer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sticker')
    op.drop_table('item_full_export')
    # ### end Alembic commands ###
