"""add steam tables

Revision ID: 29748e70cb95
Revises: cf9a9ac0768c
Create Date: 2024-10-27 02:26:53.049966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29748e70cb95'
down_revision: Union[str, None] = 'cf9a9ac0768c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_item',
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('_7d', sa.Boolean(), nullable=True),
    sa.Column('_14d', sa.Boolean(), nullable=True),
    sa.Column('_30d', sa.Boolean(), nullable=True),
    sa.Column('_90d', sa.Boolean(), nullable=True),
    sa.Column('_365d', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    op.create_table('steam_item_14d',
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_hash_name'], ['steam_item.market_hash_name'], ),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    op.create_table('steam_item_30d',
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_hash_name'], ['steam_item.market_hash_name'], ),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    op.create_table('steam_item_365d',
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_hash_name'], ['steam_item.market_hash_name'], ),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    op.create_table('steam_item_7d',
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_hash_name'], ['steam_item.market_hash_name'], ),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    op.create_table('steam_item_90d',
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_hash_name'], ['steam_item.market_hash_name'], ),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steam_item_90d')
    op.drop_table('steam_item_7d')
    op.drop_table('steam_item_365d')
    op.drop_table('steam_item_30d')
    op.drop_table('steam_item_14d')
    op.drop_table('steam_item')
    # ### end Alembic commands ###
