"""v3

Revision ID: aacc85b17466
Revises: db140b66c85c
Create Date: 2024-10-23 22:41:38.563321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacc85b17466'
down_revision: Union[str, None] = 'db140b66c85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_item',
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    op.add_column('item_full_export', sa.Column('avg_price', sa.Float(), nullable=True))
    op.add_column('sticker', sa.Column('avg_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker', 'avg_price')
    op.drop_column('item_full_export', 'avg_price')
    op.drop_table('simple_item')
    # ### end Alembic commands ###
