"""add hash index to meta_item mhn

Revision ID: cf9a9ac0768c
Revises: ca3226ff5d87
Create Date: 2024-10-24 22:34:04.380128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9a9ac0768c'
down_revision: Union[str, None] = 'ca3226ff5d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_meta_item_market_hash_name', 'meta_item', ['market_hash_name'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meta_item_market_hash_name', table_name='meta_item', postgresql_using='hash')
    # ### end Alembic commands ###
